[toolchain]
#channel = "nightly-2022-07-10"
#channel = "nightly-2023-08-08"
# Leonardo blink kompilerer og fungerer, men ssd1306 (bindgen- fungerer ikke)
channel = "nightly-2024-03-22"
# kompilerer ikke
#channel = "nightly-2024-04-22"
#channel = "nightly-2024-05-22"
#channel = "nightly-2024-06-22"
#channel = "nightly-2024-07-22"
# kompilerer - men fungerer ikke
#channel = "nightly-2024-08-22"
#channel = "nightly-2024-09-01"
components = ["rust-src"]
profile = "minimal"
