[toolchain]
#channel = "nightly-2022-07-10"
#channel = "nightly-2023-08-08"
# Leonardo seems to work
#channel = "nightly-2024-09-01"
channel = "nightly-2024-09-22"
components = ["rust-src"]
profile = "minimal"
