/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    #[link_name = "\u{1}_Z12arduino_initv"]
    pub fn arduino_init();
}
extern "C" {
    #[link_name = "\u{1}_Z17arduino_attachUSBv"]
    pub fn arduino_attachUSB();
}
extern "C" {
    #[link_name = "\u{1}_Z22arduino_serialEventRunv"]
    pub fn arduino_serialEventRun();
}
extern "C" {
    #[link_name = "\u{1}_Z12check_serialv"]
    pub fn check_serial() -> bool;
}
